# Buildpack API version
api = "0.2"

# Buildpack ID and metadata
[buildpack]
id = "samples/buildpack-justfile"
version = "0.1.0"
name = "justfile Buildpack"
homepage = "https://github.com/linux-china/buildpack-justfile"

# Stacks that the buildpack will work with
[[stacks]]
id = "io.buildpacks.stacks.bionic"

[[stacks]]
id = "heroku-18"

[[stacks]]
id = "heroku-20"
